### ISSUE TITLE
missing node.dll

### ISSUE THREAD

**Issue by steltenpower** [enjalot/served#1]
Served-x64.exe - System Error

The program can't start because node.dll is missing from your
computer. Try reinstalling the program to fix this problem.

![missingnodeerror](https://cloud.githubusercontent.com/assets/2406187/12676350/caead986-c691-11e5-9ebd-3d5eaa6ab4ce.png)

**Comment by enjalot** [comment]
Oops, can you try downloading again? I uploaded a zip of the whole folder produced by electron this time. I don't have Windows handy to test

**Comment by enjalot** [comment]
going to close, feel free to reopen if you still have an issue!

**Comment by steltenpower** [comment]
fixed indeed
