### ISSUE TITLE
httpS for browserfunctionality that requires it?

### ISSUE THREAD

**Issue by steltenpower** [enjalot/served#7]
I think Chrome requires httpS for accessing webcam.
Does it make an exception for localhost?
If not, that is a limitation of SERVED.

**Comment by enjalot** [comment]
I just tested and I can use the webcam without warning on localhost with no `https`. I don't think this is an issue during local development, only when dealing with production environments. You can also access `https` urls from `http` but not vice-versa.
going to close for now. feel free to reopen with some sample code that breaks!
